#ifndef LM_PACKETFLAGS_H_
#define LM_PACKETFLAGS_H_

#define LM_PACKET_FLAG_TRACK1				0x00
#define LM_PACKET_FLAG_TRACK2			    0x80
#define LM_PACKET_FLAG_STARTSTOPCONTROL		0x40
#define LM_PACKET_FLAG_START    			0x20
#define LM_PACKET_FLAG_STOP    				0x00

#endif /*LM_PACKETFLAGS_H_*/
